development:
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: multiplyme_development
  pool: 5
  timeout: 5000
#  username: Fraser

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: multiplyme_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: multiplyme_production
  pool: 5
  username:
  password:

